# Generated by Django 4.2.7 on 2026-02-24 17:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0002_alter_user_managers_profile_otp_invitation"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=200)),
                (
                    "sku",
                    models.CharField(
                        db_index=True,
                        help_text="Stock Keeping Unit - unique per vendor",
                        max_length=50,
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        help_text="UPC, EAN, or ISBN barcode",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("short_description", models.CharField(blank=True, max_length=255)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("physical", "Physical Product"),
                            ("digital", "Digital Download"),
                            ("service", "Service"),
                            ("bundled", "Bundled Product"),
                        ],
                        default="physical",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Selling price",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "compare_at_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Original price for showing discounts",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Your cost (for profit calculations)",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_taxable", models.BooleanField(default=True)),
                (
                    "tax_class",
                    models.CharField(blank=True, default="standard", max_length=50),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_on_sale", models.BooleanField(default=False)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Main product image",
                        null=True,
                        upload_to="products/",
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("slug", models.SlugField(blank=True, max_length=250)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="inventory.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        help_text="The vendor that owns this record",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="accounts.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "inventory_product",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="inventory",
                        serialize=False,
                        to="inventory.product",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=0,
                        help_text="Current stock quantity",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "reserved_quantity",
                    models.IntegerField(
                        default=0,
                        help_text="Quantity reserved for pending orders",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "reorder_level",
                    models.IntegerField(
                        default=10,
                        help_text="Quantity at which to reorder",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "reorder_quantity",
                    models.IntegerField(
                        default=0, help_text="Quantity to order when reordering"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Warehouse/shelf/bin location",
                        max_length=100,
                    ),
                ),
                ("last_restocked", models.DateTimeField(blank=True, null=True)),
                ("last_counted", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Inventory",
                "verbose_name_plural": "Inventories",
                "db_table": "inventory_inventory",
            },
        ),
        migrations.CreateModel(
            name="InventoryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_quantity", models.IntegerField()),
                ("new_quantity", models.IntegerField()),
                ("change", models.IntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("sale", "Sale"),
                            ("purchase", "Purchase Order"),
                            ("adjustment", "Manual Adjustment"),
                            ("return", "Customer Return"),
                            ("damage", "Damage/Loss"),
                            ("count", "Inventory Count"),
                            ("transfer", "Stock Transfer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_logs",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_inventory_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["vendor", "sku"], name="inventory_p_vendor__335e8a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["vendor", "is_active"], name="inventory_p_vendor__75eff3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["vendor", "category"], name="inventory_p_vendor__d3ae37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="inventory_p_name_f6a6a1_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("vendor", "sku")},
        ),
        migrations.AddIndex(
            model_name="inventorylog",
            index=models.Index(
                fields=["product", "created_at"], name="inventory_i_product_810f8e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorylog",
            index=models.Index(fields=["reason"], name="inventory_i_reason_a157b9_idx"),
        ),
        migrations.AddIndex(
            model_name="inventorylog",
            index=models.Index(
                fields=["created_by"], name="inventory_i_created_608975_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(
                fields=["quantity", "reorder_level"],
                name="inventory_i_quantit_096933_idx",
            ),
        ),
    ]
