# Generated by Django 4.2.7 on 2026-02-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_purchaseorder_sale_alter_category_vendor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="total",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=10
            ),
        ),
    ]
