# Generated by Django 6.0.2 on 2026-02-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_purchaseorderitem_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saleitem",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=10
            ),
        ),
    ]
