# Generated by Django 6.0.2 on 2026-03-11 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_warehouse_promotion_customer"),
        ("inventory", "0007_producttag_return_warehouse_and_more"),
    ]

    operations = []
