# Generated by Django 4.2.25 on 2026-04-26 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_managers_profile_otp_invitation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0008_merge_20260311_0928"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("low_stock", "Low Stock Alert"),
                            ("sale_created", "New Sale"),
                            ("sale_large", "Large Sale Alert"),
                            ("po_created", "Purchase Order Created"),
                            ("po_received", "Purchase Order Received"),
                            ("po_status", "Purchase Order Status Update"),
                            ("product_created", "Product Created"),
                            ("inventory_adjusted", "Inventory Adjusted"),
                            ("system", "System Notification"),
                            ("info", "Information"),
                            ("warning", "Warning"),
                        ],
                        db_index=True,
                        default="info",
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("action_url", models.CharField(blank=True, max_length=500)),
                ("related_object_type", models.CharField(blank=True, max_length=50)),
                ("related_object_id", models.IntegerField(blank=True, null=True)),
                ("icon", models.CharField(default="🔔", max_length=10)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "inventory_notification",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["vendor", "user", "is_read"],
                name="inventory_n_vendor__ffa25c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["vendor", "notification_type"],
                name="inventory_n_vendor__a7647c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["created_at"], name="inventory_n_created_c407b9_idx"
            ),
        ),
    ]

