# Generated by Django 4.2.7 on 2026-02-27 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0002_alter_user_managers_profile_otp_invitation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("sales_summary", "Sales Summary"),
                            ("inventory_status", "Inventory Status"),
                            ("profit_loss", "Profit & Loss"),
                            ("low_stock", "Low Stock Alert"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        blank=True, help_text="0=Monday, 6=Sunday", null=True
                    ),
                ),
                (
                    "day_of_month",
                    models.IntegerField(blank=True, help_text="1-31", null=True),
                ),
                ("time_of_day", models.TimeField(default="09:00")),
                (
                    "format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("csv", "CSV")],
                        default="pdf",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_sent", models.DateTimeField(blank=True, null=True)),
                ("next_send", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_schedules",
                        to="accounts.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "reports_schedule",
            },
        ),
        migrations.CreateModel(
            name="SalesReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "total_sales",
                    models.IntegerField(default=0, help_text="Number of transactions"),
                ),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "average_order_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "top_products",
                    models.JSONField(default=dict, help_text="Top selling products"),
                ),
                (
                    "products_sold",
                    models.IntegerField(default=0, help_text="Total units sold"),
                ),
                ("unique_customers", models.IntegerField(default=0)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_final",
                    models.BooleanField(
                        default=False, help_text="Whether this is final or preliminary"
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_reports",
                        to="accounts.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "reports_sales",
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(
                        fields=["vendor", "-start_date"],
                        name="reports_sal_vendor__5f5c30_idx",
                    ),
                    models.Index(
                        fields=["vendor", "period"],
                        name="reports_sal_vendor__a6266f_idx",
                    ),
                ],
                "unique_together": {("vendor", "period", "start_date", "end_date")},
            },
        ),
        migrations.CreateModel(
            name="InventoryValuation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "total_items",
                    models.IntegerField(
                        default=0, help_text="Total number of items in stock"
                    ),
                ),
                (
                    "total_products",
                    models.IntegerField(
                        default=0, help_text="Number of unique products"
                    ),
                ),
                (
                    "value_at_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "value_at_retail",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "potential_profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("low_stock_count", models.IntegerField(default=0)),
                ("out_of_stock_count", models.IntegerField(default=0)),
                ("by_category", models.JSONField(default=dict)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_valuations",
                        to="accounts.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "reports_inventory_valuation",
                "ordering": ["-date"],
                "unique_together": {("vendor", "date")},
            },
        ),
    ]
